class Questionlist {
  List questionlist = [
    {'que_no': 1, 'question': 'Question 1', 'answer': 'True'},
    {'que_no': 2, 'question': 'Question 2', 'answer': 'False'},
    {'que_no': 3, 'question': 'Question 3', 'answer': 'True'},
    {'que_no': 4, 'question': 'Question 4', 'answer': 'False'},
    {'que_no': 5, 'question': 'Question 5', 'answer': 'True'},
    {'que_no': 6, 'question': 'Question 6', 'answer': 'False'},
    {'que_no': 7, 'question': 'Question 7', 'answer': 'True'},
    {'que_no': 8, 'question': 'Question 8', 'answer': 'False'},
    {'que_no': 9, 'question': 'Question 9', 'answer': 'True'},
    {'que_no': 10, 'question': 'Question 10', 'answer': 'False'},
  ];
}

class MCQList {
  List mcqList = [
    {
      'que_no': 1,
      'question': 'Question 1',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 2,
      'question': 'Question 2',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 3,
      'question': 'Question 3',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 4,
      'question': 'Question 4',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 5,
      'question': 'Question 5',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 6,
      'question': 'Question 6',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 7,
      'question': 'Question 7',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 8,
      'question': 'Question 8',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 9,
      'question': 'Question 9',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
    {
      'que_no': 10,
      'question': 'Question 10',
      'option 1': 'OPTION 1',
      'option 2': 'OPTION 2',
      'option 3': 'OPTION 3',
      'option 4': 'OPTION 4',
      'answer': 'OPTION 1',
    },
  ];
}
